import Head from 'next/head'
import styles from '@/styles/Home.module.scss'
import Form from '@/components/Home/form/form'
import LoginImage from '@/components/Home/imageBack/image'

export default function Home() {

  return (
    <>
      <Head>
        <title>Calamian MDs Pharmacy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <LoginImage />
        <Form />
      </div>
    </>
  )
}
